// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL7XhIT037EFCX7HYhTq6vw1xP4ss2sQ0',
    appId: '1:308377914214:web:ad1d021dc9bdbbdb2496a7',
    messagingSenderId: '308377914214',
    projectId: 'donation-app-89449',
    authDomain: 'donation-app-89449.firebaseapp.com',
    storageBucket: 'donation-app-89449.appspot.com',
    measurementId: 'G-HE1XE64SH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfgYvi6_8iSpd3DDwiyrjILQUe0nCqUgk',
    appId: '1:308377914214:android:9f0b6c9a0738744c2496a7',
    messagingSenderId: '308377914214',
    projectId: 'donation-app-89449',
    storageBucket: 'donation-app-89449.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPtP_gBFGQswLicZwxsZX-MFqQ6-XZ3J4',
    appId: '1:308377914214:ios:925154850298ddf22496a7',
    messagingSenderId: '308377914214',
    projectId: 'donation-app-89449',
    storageBucket: 'donation-app-89449.appspot.com',
    iosBundleId: 'com.example.appDevProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPtP_gBFGQswLicZwxsZX-MFqQ6-XZ3J4',
    appId: '1:308377914214:ios:c62a8d8358d6770e2496a7',
    messagingSenderId: '308377914214',
    projectId: 'donation-app-89449',
    storageBucket: 'donation-app-89449.appspot.com',
    iosBundleId: 'com.example.appDevProject.RunnerTests',
  );
}
